version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: docker/Dockerfile
        container_name: laravel_api
        restart: unless-stopped
        working_dir: /var/www/html
        volumes:
            - .:/var/www/html
        networks:
            - api-network
        environment:
            - PHP_OPCACHE_ENABLE=1

    webserver:
        image: nginx:alpine
        container_name: api_nginx
        restart: unless-stopped
        ports:
            - "8000:80"
        volumes:
            - .:/var/www/html
            - ./docker/nginx/app.conf:/etc/nginx/conf.d/default.conf
        networks:
            - api-network
        depends_on:
            - app

    db:
        image: mysql:8.0
        container_name: api_mysql
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: laravel_api
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_PASSWORD: secret
            MYSQL_USER: api_user
        volumes:
            - mysql_data:/var/lib/mysql
        networks:
            - api-network
        ports:
            - "3306:3306"

volumes:
    mysql_data:
        driver: local

networks:
    api-network:
        driver: bridge
